pokemon:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: public
      threads: 1
      keepalives_idle: 0 # default 0
      connect_timeout: 10 # default 10 seconds
